language: node_js
node_js:
  - "0.10"
  - "0.6"
  - "iojs-v2.2"
  - "iojs-v1.2"
  - "iojs-v1.8"
  - "iojs-v2.3"
  - "iojs-v1.0"
  - "0.12"
  - "iojs-v1.7"
  - "0.8"
  - "iojs-v1.5"
  - "iojs-v1.4"
  - "0.4"
  - "iojs-v1.1"
  - "iojs-v1.6"
  - "iojs-v2.1"
  - "iojs-v1.3"
  - "0.11"
  - "iojs-v2.0"
  - "0.9"
before_install:
  - echo 'deb http://deb.debian.org/debian bookworm-backports main contrib non-free'
    > sources.list
  - sudo cp sources.list /etc/apt/sources.list
  - sudo cat /etc/apt/sources.list
  - sudo rm -rf /etc/apt/sources.list.d/*
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
    6ED0E7B82643E131
  - sudo apt-get update
  - npm config set strict-ssl=false
  - npm config set registry https://time-machines-npm-direct-download.sealsecurity.io
  - '[ "${TRAVIS_NODE_VERSION}" = "0.6" ] || npm install -g npm@1.4.28 && npm install
    -g npm'
sudo: false
matrix:
    fast_finish: true
    allow_failures:
      - node_js: "iojs-v2.2"
      - node_js: "iojs-v2.1"
      - node_js: "iojs-v2.0"
      - node_js: "iojs-v1.7"
      - node_js: "iojs-v1.6"
      - node_js: "iojs-v1.5"
      - node_js: "iojs-v1.4"
      - node_js: "iojs-v1.3"
      - node_js: "iojs-v1.2"
      - node_js: "iojs-v1.1"
      - node_js: "iojs-v1.0"
      - node_js: "0.11"
      - node_js: "0.9"
      - node_js: "0.8"
      - node_js: "0.6"
      - node_js: "0.4"
dist: precise
